ALTER TABLE monitors ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE monitors ADD COLUMN notify_email BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE monitors ADD COLUMN notify_sms BOOLEAN NOT NULL DEFAULT TRUE;